### PR TITLE
Switch to official java:8-jre-alpine image in Dockerfile

### PR DESCRIPTION
**Pull request by devth**
Replaces #62

### CODE REVIEW

**Comment by gardnervickers** [comment]
@devth Thanks for the PR, can you verify that this starts up correctly with `docker-compose`?

**Comment by devth** [comment]
It doesn't appear to work, but I'm not sure if it's related to switching out images:

``` bash
Starting myonyxapp_zookeeper_1
Creating myonyxapp_peer_1
Attaching to myonyxapp_zookeeper_1, myonyxapp_peer_1
zookeeper_1  | JMX enabled by default
zookeeper_1  | Using config: /opt/zookeeper-3.4.6/bin/../conf/zoo.cfg
peer_1       | [fix-attrs.d] applying owners & permissions fixes...
peer_1       | [fix-attrs.d] 00-runscripts: applying...
peer_1       | [fix-attrs.d] 00-runscripts: exited 0.
peer_1       | [fix-attrs.d] done.
peer_1       | [cont-init.d] executing container initialization scripts...
peer_1       | [cont-init.d] done.
peer_1       | [services.d] starting services
peer_1       | [services.d] done.
peer_1       | s6-supervise media_driver: warning: unable to spawn ./run - waiting 10 seconds
peer_1       | s6-supervise (child): fatal: unable to exec run: No such file or directory
zookeeper_1  | 2016-06-13 15:38:15,807 [myid:] - INFO  [main:QuorumPeerConfig@103] - Reading configuration from: /opt/zookeeper-3.4.6/bin/../conf/zoo.cfg
zookeeper_1  | 2016-06-13 15:38:15,811 [myid:] - INFO  [main:DatadirCleanupManager@78] - autopurge.snapRetainCount set to 3
zookeeper_1  | 2016-06-13 15:38:15,813 [myid:] - INFO  [main:DatadirCleanupManager@79] - autopurge.purgeInterval set to 1
zookeeper_1  | 2016-06-13 15:38:15,818 [myid:] - WARN  [main:QuorumPeerMain@113] - Either no config or no quorum defined in config, running  in standalone mode
zookeeper_1  | 2016-06-13 15:38:15,820 [myid:] - INFO  [PurgeTask:DatadirCleanupManager$PurgeTask@138] - Purge task started.
zookeeper_1  | 2016-06-13 15:38:15,864 [myid:] - INFO  [PurgeTask:DatadirCleanupManager$PurgeTask@144] - Purge task completed.
zookeeper_1  | 2016-06-13 15:38:15,867 [myid:] - INFO  [main:QuorumPeerConfig@103] - Reading configuration from: /opt/zookeeper-3.4.6/bin/../conf/zoo.cfg
zookeeper_1  | 2016-06-13 15:38:15,869 [myid:] - INFO  [main:ZooKeeperServerMain@95] - Starting server
zookeeper_1  | 2016-06-13 15:38:15,881 [myid:] - INFO  [main:Environment@100] - Server environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
zookeeper_1  | 2016-06-13 15:38:15,894 [myid:] - INFO  [main:Environment@100] - Server environment:host.name=c387ffdce8cd
zookeeper_1  | 2016-06-13 15:38:15,894 [myid:] - INFO  [main:Environment@100] - Server environment:java.version=1.7.0_65
zookeeper_1  | 2016-06-13 15:38:15,895 [myid:] - INFO  [main:Environment@100] - Server environment:java.vendor=Oracle Corporation
zookeeper_1  | 2016-06-13 15:38:15,895 [myid:] - INFO  [main:Environment@100] - Server environment:java.home=/usr/lib/jvm/java-7-openjdk-amd64/jre
zookeeper_1  | 2016-06-13 15:38:15,896 [myid:] - INFO  [main:Environment@100] - Server environment:java.class.path=/opt/zookeeper-3.4.6/bin/../build/classes:/opt/zookeeper-3.4.6/bin/../build/lib/*.jar:/opt/zookeeper-3.4.6/bin/../lib/slf4j-log4j12-1.6.1.jar:/opt/zookeeper-3.4.6/bin/../lib/slf4j-api-1.6.1.jar:/opt/zookeeper-3.4.6/bin/../lib/netty-3.7.0.Final.jar:/opt/zookeeper-3.4.6/bin/../lib/log4j-1.2.16.jar:/opt/zookeeper-3.4.6/bin/../lib/jline-0.9.94.jar:/opt/zookeeper-3.4.6/bin/../zookeeper-3.4.6.jar:/opt/zookeeper-3.4.6/bin/../src/java/lib/*.jar:/opt/zookeeper-3.4.6/bin/../conf:
zookeeper_1  | 2016-06-13 15:38:15,897 [myid:] - INFO  [main:Environment@100] - Server environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
zookeeper_1  | 2016-06-13 15:38:15,897 [myid:] - INFO  [main:Environment@100] - Server environment:java.io.tmpdir=/tmp
zookeeper_1  | 2016-06-13 15:38:15,900 [myid:] - INFO  [main:Environment@100] - Server environment:java.compiler=<NA>
zookeeper_1  | 2016-06-13 15:38:15,901 [myid:] - INFO  [main:Environment@100] - Server environment:os.name=Linux
zookeeper_1  | 2016-06-13 15:38:15,901 [myid:] - INFO  [main:Environment@100] - Server environment:os.arch=amd64
zookeeper_1  | 2016-06-13 15:38:15,902 [myid:] - INFO  [main:Environment@100] - Server environment:os.version=4.4.8-boot2docker
zookeeper_1  | 2016-06-13 15:38:15,902 [myid:] - INFO  [main:Environment@100] - Server environment:user.name=root
zookeeper_1  | 2016-06-13 15:38:15,903 [myid:] - INFO  [main:Environment@100] - Server environment:user.home=/root
zookeeper_1  | 2016-06-13 15:38:15,903 [myid:] - INFO  [main:Environment@100] - Server environment:user.dir=/opt/zookeeper-3.4.6
zookeeper_1  | 2016-06-13 15:38:15,904 [myid:] - INFO  [main:ZooKeeperServer@755] - tickTime set to 2000
zookeeper_1  | 2016-06-13 15:38:15,905 [myid:] - INFO  [main:ZooKeeperServer@764] - minSessionTimeout set to -1
zookeeper_1  | 2016-06-13 15:38:15,905 [myid:] - INFO  [main:ZooKeeperServer@773] - maxSessionTimeout set to -1
zookeeper_1  | 2016-06-13 15:38:15,955 [myid:] - INFO  [main:NIOServerCnxnFactory@94] - binding to port 0.0.0.0/0.0.0.0:2181
peer_1       | Starting peer-group
peer_1       | 16-Jun-13 15:38:24 5ed5e933e8fc INFO [onyx.static.logging-configuration] - Starting Logging Configuration
peer_1       | 16-Jun-13 15:38:24 5ed5e933e8fc INFO [onyx.messaging.aeron] - Starting Aeron Peer Group
peer_1       |
peer_1       | ***
peer_1       | *** Failed to connect to the Media Driver - is it currently running?
peer_1       | ***
peer_1       | 16-Jun-13 15:38:24 5ed5e933e8fc FATAL [onyx.system] -
peer_1       |                          my_onyx_app.core.main
peer_1       |                                            ...
peer_1       |                         my-onyx-app.core/-main        core.clj:   67
peer_1       |                         my-onyx-app.core/-main        core.clj:   77
peer_1       |                       lib-onyx.peer/start-peer        peer.clj:    7
peer_1       |                      onyx.api/start-peer-group         api.clj:  376
peer_1       |                onyx.system.OnyxPeerGroup/start      system.clj:  100
peer_1       |                  onyx.system/rethrow-component      system.clj:   56
peer_1       |                   onyx.system.OnyxPeerGroup/fn      system.clj:  101
peer_1       |        com.stuartsierra.component/start-system  component.cljc:  163
peer_1       |                                            ...
peer_1       |       com.stuartsierra.component/update-system  component.cljc:  129
peer_1       |       com.stuartsierra.component/update-system  component.cljc:  135
peer_1       |                            clojure.core/reduce        core.clj: 6544
peer_1       |                                            ...
peer_1       |    com.stuartsierra.component/update-system/fn  component.cljc:  139
peer_1       |          com.stuartsierra.component/try-action  component.cljc:  117
peer_1       |                             clojure.core/apply        core.clj:  648
peer_1       |                                            ...
peer_1       |                com.stuartsierra.component/fn/G  component.cljc:    5 (repeats 2 times)
peer_1       |      onyx.messaging.aeron.AeronPeerGroup/start       aeron.clj:  214
peer_1       |                              clojure.core/mapv        core.clj: 6618
peer_1       |                            clojure.core/reduce        core.clj: 6544
peer_1       |                                            ...
peer_1       |                           clojure.core/mapv/fn        core.clj: 6627
peer_1       |         onyx.messaging.aeron.AeronPeerGroup/fn       aeron.clj:  215
peer_1       |         onyx.messaging.aeron/start-subscriber!       aeron.clj:  170
peer_1       |           uk.co.real_logic.aeron.Aeron.connect      Aeron.java:  112
peer_1       |            uk.co.real_logic.aeron.Aeron.<init>      Aeron.java:   70
peer_1       |  uk.co.real_logic.aeron.Aeron$Context.conclude      Aeron.java:  210
peer_1       | uk.co.real_logic.agrona.IoUtil.mapExistingFile     IoUtil.java:  247
peer_1       | uk.co.real_logic.agrona.IoUtil.checkFileExists     IoUtil.java:  328
peer_1       | java.lang.IllegalStateException: Missing file for cnc: /dev/shm/aeron-root/cnc
peer_1       | java.lang.IllegalStateException: Could not initialise communication buffers
peer_1       |      clojure.lang.ExceptionInfo: Error in component :messaging-group in system onyx.system.OnyxPeerGroup calling #'com.stuartsierra.component/start
peer_1       |      component: #<Aeron Peer Group>
peer_1       |       function: #'com.stuartsierra.component/start
peer_1       |         reason: :com.stuartsierra.component/component-function-threw-exception
peer_1       |         system: #onyx.system.OnyxPeerGroup{:config {:onyx/tenancy-id "1", :onyx.messaging/allow-short-circuit? false, :onyx.messaging/impl :aeron, :onyx.log/config {:level :info}, :onyx.messaging/peer-port 40200, :zookeeper/address "zookeeper:2181", :onyx.peer/job-scheduler :onyx.job-scheduler/greedy, :onyx.messaging.aeron/embedded-driver? false, :onyx.peer/zookeeper-timeout 60000, :onyx.messaging/bind-addr "localhost"}, :logging-config #<Logging Configuration>, :messaging-group #<Aeron Peer Group>}
peer_1       |     system-key: :messaging-group
peer_1       |
peer_1       | Exception in thread "main" java.lang.IllegalStateException: Could not initialise communication buffers
peer_1       |  at uk.co.real_logic.aeron.Aeron$Context.conclude(Aeron.java:270)
peer_1       |  at uk.co.real_logic.aeron.Aeron.<init>(Aeron.java:70)
peer_1       |  at uk.co.real_logic.aeron.Aeron.connect(Aeron.java:112)
peer_1       |  at onyx.messaging.aeron$start_subscriber_BANG_.invokeStatic(aeron.clj:170)
peer_1       |  at onyx.messaging.aeron$start_subscriber_BANG_.invoke(aeron.clj:167)
peer_1       |  at onyx.messaging.aeron.AeronPeerGroup$fn__15686.invoke(aeron.clj:215)
peer_1       |  at clojure.core$mapv$fn__6953.invoke(core.clj:6627)
peer_1       |  at clojure.lang.LongRange.reduce(LongRange.java:233)
peer_1       |  at clojure.core$reduce.invokeStatic(core.clj:6544)
peer_1       |  at clojure.core$mapv.invokeStatic(core.clj:6618)
peer_1       |  at clojure.core$mapv.invoke(core.clj:6618)
peer_1       |  at onyx.messaging.aeron.AeronPeerGroup.start(aeron.clj:214)
peer_1       |  at com.stuartsierra.component$fn__6829$G__6823__6831.invoke(component.cljc:5)
peer_1       |  at com.stuartsierra.component$fn__6829$G__6822__6834.invoke(component.cljc:5)
peer_1       |  at clojure.lang.Var.invoke(Var.java:379)
peer_1       |  at clojure.lang.AFn.applyToHelper(AFn.java:154)
peer_1       |  at clojure.lang.Var.applyTo(Var.java:700)
peer_1       |  at clojure.core$apply.invokeStatic(core.clj:648)
peer_1       |  at clojure.core$apply.invoke(core.clj:641)
peer_1       |  at com.stuartsierra.component$try_action.invokeStatic(component.cljc:117)
peer_1       |  at com.stuartsierra.component$try_action.invoke(component.cljc:116)
peer_1       |  at com.stuartsierra.component$update_system$fn__6880.invoke(component.cljc:139)
peer_1       |  at clojure.lang.ArraySeq.reduce(ArraySeq.java:114)
peer_1       |  at clojure.core$reduce.invokeStatic(core.clj:6544)
peer_1       |  at clojure.core$reduce.invoke(core.clj:6527)
peer_1       |  at com.stuartsierra.component$update_system.invokeStatic(component.cljc:135)
peer_1       |  at com.stuartsierra.component$update_system.doInvoke(component.cljc:129)
peer_1       |  at clojure.lang.RestFn.invoke(RestFn.java:445)
peer_1       |  at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163)
peer_1       |  at com.stuartsierra.component$start_system.invoke(component.cljc:155)
peer_1       |  at onyx.system.OnyxPeerGroup$fn__20446.invoke(system.clj:101)
peer_1       |  at onyx.system$rethrow_component.invokeStatic(system.clj:56)
peer_1       |  at onyx.system$rethrow_component.invoke(system.clj:54)
peer_1       |  at onyx.system.OnyxPeerGroup.start(system.clj:100)
peer_1       |  at onyx.api$start_peer_group.invokeStatic(api.clj:376)
peer_1       |  at onyx.api$start_peer_group.invoke(api.clj:371)
peer_1       |  at lib_onyx.peer$start_peer.invokeStatic(peer.clj:7)
peer_1       |  at lib_onyx.peer$start_peer.invoke(peer.clj:4)
peer_1       |  at my_onyx_app.core$_main.invokeStatic(core.clj:77)
peer_1       |  at my_onyx_app.core$_main.doInvoke(core.clj:67)
peer_1       |  at clojure.lang.RestFn.applyTo(RestFn.java:137)
peer_1       |  at my_onyx_app.core.main(Unknown Source)
peer_1       | Caused by: java.lang.IllegalStateException: Missing file for cnc: /dev/shm/aeron-root/cnc
peer_1       |  at uk.co.real_logic.agrona.IoUtil.checkFileExists(IoUtil.java:328)
peer_1       |  at uk.co.real_logic.agrona.IoUtil.mapExistingFile(IoUtil.java:247)
peer_1       |  at uk.co.real_logic.aeron.Aeron$Context.conclude(Aeron.java:210)
peer_1       |  ... 41 more
peer_1       | s6-supervise media_driver: warning: unable to spawn ./run - waiting 10 seconds
peer_1       | s6-supervise (child): fatal: unable to exec run: No such file or directory
```

**Comment by gardnervickers** [comment]
```
peer_1       | s6-supervise media_driver: warning: unable to spawn ./run - waiting 10 seconds
peer_1       | s6-supervise (child): fatal: unable to exec run: No such file or directory
```

The upstart process is not starting the media driver with the official java-alpine image.

**Comment by gardnervickers** [comment]
This was my fault, one of the scripts was using `bash` which was not installed. Fixed

**Pull request closed without merging**
